### ISSUE TITLE
covid19.data Does Not Execute in AWS EC2

### ISSUE THREAD

**Issue by ZellW** [mponce0/covid19.analytics#5]
Is there a library dependency that prevents package executables from existing in AWS EC2?  All dependent packages are loaded but data does not update.  I am guessing a Linux library dependency is missing in the package documentation.

**Comment by mponce0** [comment]
Hi Cliff,

Thanks for reporting this.
Can you provide me an example of what is failing for you?
Also what OS are you running on the instance of AWS?

Regards,
Marcelo

**Comment by ZellW** [comment]
Thanks for the quick reply.
I am running an Ubuntu Server on AWS EC2:  ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server
This code runs perfectly locally but does not execute on the VM:
`covid_data_agg_wide <- covid19.data(case = "aggregated", local.data = FALSE, debrief = FALSE)`
No error is returned and the page displays without error but the data is old - it does not update.
https://shiny.cliffweaver.com/covid/#section-summary
All I can think is a Linux library may be missing.

**Comment by ZellW** [comment]
It might also be a port problem. Are any specific ports required ?

**Comment by mponce0** [comment]
Thanks for the details and great looking dashboard!
It is strange, are the other cases working? eg cases="TS-all"?
The function underneath uses a call to R basics read.csv() so as far as I'm aware nothing special should be needed nor a particular port. Does the VM has internet access? Otherwise that would explain why the data is not being updated as the function contacts and grab the latest updates from the JHU repo and if it is not available then brings data locally stored in the package, I believe it should warn you about it though.

**Comment by mponce0** [comment]
WRT libraries that could be needed, libcurl -- https://packages.ubuntu.com/bionic/libcurl-dev -- should be there, but I believe R (if you compiled from source) may have taken care of this...

As a test case for the connectivity of the VM, can you try the following command from the shell,

curl -L -O  https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-14-2020.csv

that should download the CSV file accessed by the package directly.

Or from an R session,

system("curl -L -O  https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-14-2020.csv")

if any of these fails then something is not

**Comment by ZellW** [comment]
`curl -L -O https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-14-2020.csv` works.  

`libcurl `is available.

I had considered downloading the JHU files directly, but I would prefer to leverage all the data cleanup you did, specifically with the timeseries data.

**Comment by mponce0** [comment]
OK, can you try now from an R session,

jhu.data <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-14-2020.csv")

and see if it works...?
Yeah, the issue of cleaning and homogenizing the data is one of the main goals of the package, specially considering that sometimes CCSE changes something with the data formats...

**Comment by ZellW** [comment]
Yes, that works.

**Comment by mponce0** [comment]
Sorry for so many questions, but would you mind trying the command,

covid_data_agg_wide <- covid19.data(case = "aggregated", local.data = FALSE, debrief = TRUE)

and paste the output... my guess is that the function covid19.data may be failing at some point but the tryCatch() exception clause may be catching the wrong symptom and grabbing the local data instead.

One more thing which version of covid19.analytics are you using? There is a recent one 1.1.1 on CRAN or the one directly from the GitHub repo which you may want to try.

**Comment by ZellW** [comment]
I love the questions.  Running version 1.1.  Will upgrade to 1.1.1 now and see if data updates.  Will do this now.  Then will do the other test.

**Comment by ZellW** [comment]
`covid_data_agg_wide <- covid19.data(case = "aggregated", local.data = FALSE, debrief = TRUE)` works!

Now I am thinking there may be a problem with flexdashboard/shiny.  Let me try a few different avenues.  You have done everything you can.  I do not think it is `covid19.analytics`.  So sorry to use your time.  OK to close.  Will report back if I find a solution.

 library("covid19.analytics")
> covid_data_agg_wide <- covid19.data(case = "aggregated", local.data = FALSE, debrief = TRUE)
Data being read from JHU/CCSE repository
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Reading data from https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/07-15-2020.csv
'data.frame':   3822 obs. of  14 variables:
 $ FIPS               : int  45001 22001 51001 16001 19001 21001 29001 40001 8001 16003 ...
 $ Admin2             : chr  "Abbeville" "Acadia" "Accomack" "Ada" ...
 $ Province_State     : chr  "South Carolina" "Louisiana" "Virginia" "Idaho" ...
 $ Country_Region     : chr  "US" "US" "US" "US" ...
 $ Last_Update        : chr  "2020-07-16 04:44:59" "2020-07-16 04:44:59" "2020-07-16 04:44:59" "2020-07-16 04:44:59" ...
 $ Lat                : num  34.2 30.3 37.8 43.5 41.3 ...
 $ Long_              : num  -82.5 -92.4 -75.6 -116.2 -94.5 ...
 $ Confirmed          : int  165 1510 1045 4836 17 151 103 160 4916 12 ...
 $ Deaths             : int  1 46 14 28 0 19 0 4 159 0 ...
 $ Recovered          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Active             : int  164 1464 1031 4808 17 132 103 156 4757 12 ...
 $ Combined_Key       : chr  "Abbeville, South Carolina, US" "Acadia, Louisiana, US" "Accomack, Virginia, US" "Ada, Idaho, US" ...
 $ Incidence_Rate     : num  673 2434 3234 1004 238 ...
 $ Case.Fatality_Ratio: num  0.606 3.046 1.34 0.579 0 ...
NULL
   FIPS    Admin2 Province_State Country_Region         Last_Update      Lat
1 45001 Abbeville South Carolina             US 2020-07-16 04:44:59 34.22333
2 22001    Acadia      Louisiana             US 2020-07-16 04:44:59 30.29506
3 51001  Accomack       Virginia             US 2020-07-16 04:44:59 37.76707
4 16001       Ada          Idaho             US 2020-07-16 04:44:59 43.45266
5 19001     Adair           Iowa             US 2020-07-16 04:44:59 41.33076
6 21001     Adair       Kentucky             US 2020-07-16 04:44:59 37.10460
       Long_ Confirmed Deaths Recovered Active                  Combined_Key
1  -82.46171       165      1         0    164 Abbeville, South Carolina, US
2  -92.41420      1510     46         0   1464         Acadia, Louisiana, US
3  -75.63235      1045     14         0   1031        Accomack, Virginia, US
4 -116.24155      4836     28         0   4808                Ada, Idaho, US
5  -94.47106        17      0         0     17               Adair, Iowa, US
6  -85.28130       151     19         0    132           Adair, Kentucky, US
  Incidence_Rate Case.Fatality_Ratio
1       672.7280           0.6060606
2      2433.7175           3.0463576
3      3233.6923           1.3397129
4      1004.1799           0.5789909
5       237.6957           0.0000000
6       786.3764          12.5827815
 [1] "FIPS"                "Admin2"              "Province_State"
 [4] "Country_Region"      "Last_Update"         "Lat"
 [7] "Long_"               "Confirmed"           "Deaths"
[10] "Recovered"           "Active"              "Combined_Key"
[13] "Incidence_Rate"      "Case.Fatality_Ratio"

**Comment by mponce0** [comment]
Thanks for letting me know and certainly will be interested in your findings.
Something I've noticed with some dashboards is that they need a sort of "reactive" feature to update the data...
BTW we are working in one for the package to be deployed in ver 2.0, a teaser can be seen at https://covid19analytics.scinet.utoronto.ca

**Comment by ZellW** [comment]
Looking forward to 2.0.  Looks like I have will have more changes to make;)

I did find the problem.  Very surprising.

To hide the output from `covid19.data`,  in the flexdashboard I had `results='hide'` in the R code block.  This is supposed to be the equivalent of `results="FALSE'` but it did not work that way.  (See https://bookdown.org/yihui/rmarkdown-cookbook/hide-one.html)  Using the latter allowed `results='FALSE'` to return data!  I cannot find a reason for this but I am please my app now works.

**Comment by ZellW** [comment]
Thank you for all your support and much more thanks for `covid19.analytics`.

**Comment by mponce0** [comment]
> Looking forward to 2.0. Looks like I have will have more changes to make;)
> 
> I did find the problem. Very surprising.
> 
> To hide the output from `covid19.data`, in the flexdashboard I had `results='hide'` in the R code block. This is supposed to be the equivalent of `results="FALSE'` but it did not work that way. (See https://bookdown.org/yihui/rmarkdown-cookbook/hide-one.html) Using the latter allowed `results='FALSE'` to return data! I cannot find a reason for this but I am please my app now works.

Interesting, thank you for letting me know. I'm glad you have it working!
Most of the reading functions in covid19.analytics will communicate messages using warning() or message(), hence it should not interfere with your dashboard.

**Comment by mponce0** [comment]
> Thank you for all your support and much more thanks for `covid19.analytics`.

My pleasure!
Please feel free to let me know if you find any other issues or can think of something you could find useful in the package to implement.
Also, I'll be happy to add a section in the documentation of the package to advertise your dashboard, let me know if you would be OK with that.

**Comment by ZellW** [comment]
The package does output:

`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ `
This is why I used the `results=` in my code block.  It would be nice if that did not exists, IMHO.

**Comment by mponce0** [comment]
I see, sorry... I may have overseen that separator... will get it fixed for next release.
Thanks
